################################ CONFIG DO SERVIDOR ################################
spring.application.name=projeto-clinica
server.port=8000

############################# CONFIG DO BANCO DE DADOS #############################
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

spring.data.mongodb.authentication-database=admin
spring.data.mongodb.database=mongodb
spring.data.mongodb.username=user
spring.data.mongodb.password=password

############################# CONFIG DO EMAIL #############################
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=b6fc698acd20da
spring.mail.password=38f1a3d60f300a
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.starttls.enable = true
####################################################################################


