version: "3.8"
services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: test_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "8031:5432"
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
            PGADMIN_DEFAULT_PASSWORD: 'admin'
        ports:
            - "8032:80"